version: "3.9"
services:
  grafana:
    container_name: grafana
    restart: always
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    image: grafana/grafana:8.0.6
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - main

  prometheus:
    container_name: prometheus
    restart: always
    ports:
    - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    image: prom/prometheus
    networks:
      - main

  scraper:
    container_name: scraper
    restart: on-failure
    environment:
      METRICS_PORT: "8000"
    build: ./scraper
    networks:
      - main

  app:
    container_name: app
    restart: on-failure
    ports:
    - "5000:5000"
    environment:
      PROMETHEUS_SERVER_URL: "http://prometheus:9090"
    build: ./web
    networks:
      - main

networks:
  main:
    name: "main"

volumes:
  prometheus-data:
  grafana-data: 

